service: beneficio-joven-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-offline

functions:
  test:
    handler: src/handlers/test.handler
    timeout: 30
    events:
      - http:
          path: test
          method: get
          cors: true
  
  login:
    handler: src/handlers/auth/login.handler
    timeout: 30
    events:
      - http:
          path: auth/login
          method: post
          cors: true
  
  registerBeneficiario:
    handler: src/handlers/auth/register.handler
    timeout: 30
    events:
      - http:
          path: auth/register/beneficiario
          method: post
          cors: true
  
  registerDueno:
    handler: src/handlers/auth/register-dueno.handler
    timeout: 30
    events:
      - http:
          path: auth/register/dueno
          method: post
          cors: true
  
  registerAdmin:
    handler: src/handlers/auth/register-admin.handler
    timeout: 30
    events:
      - http:
          path: auth/register/admin
          method: post
          cors: true
  
  dashboardStats:
    handler: src/handlers/admin/dashboard-stats.handler
    timeout: 30
    events:
      - http:
          path: admin/dashboard/stats
          method: get
          cors: true

custom:
  serverless-offline:
    httpPort: 3000